# Generated by Django 5.1.7 on 2025-04-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email tidak boleh kosong.', 'required': 'Email wajib diisi.', 'unique': 'Email sudah digunakan.'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(error_messages={'blank': 'NIK tidak boleh kosong.', 'required': 'NIK wajib diisi.', 'unique': 'NIK sudah terdaftar.'}, max_length=20, unique=True),
        ),
    ]
