# Generated by Django 5.1.7 on 2025-04-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='nik',
            field=models.CharField(max_length=20),
        ),
    ]
