# Generated by Django 5.1.7 on 2025-04-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TujuanDatang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan_datang', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pendatang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(blank=True, max_length=255, null=True)),
                ('no_ktp', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('alamat_asal', models.TextField(blank=True, null=True)),
                ('alamat_sekarang', models.TextField(blank=True, null=True)),
                ('tanggal_datang', models.DateField(blank=True, null=True)),
                ('agama', models.CharField(blank=True, max_length=50, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('laki-laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], max_length=10, null=True)),
                ('phone', models.CharField(null=True)),
                ('penanggungjawab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendatangs', to=settings.AUTH_USER_MODEL)),
                ('tujuan_kedatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tujuandatang', to='api.tujuandatang')),
            ],
        ),
    ]
