# Generated by Django 5.1.7 on 2025-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tujuandatang_pendatang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_kaling',
            field=models.CharField(blank=True, choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='url_google_map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
