# Generated by Django 5.1.7 on 2025-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_status_kaling_user_url_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status_kaling',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
