# Generated by Django 5.1.7 on 2025-05-21 01:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pendatang_foto_pendatang_foto_ktp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendatang',
            name='alamat_asal',
        ),
        migrations.RemoveField(
            model_name='pendatang',
            name='kepala_lingkungan',
        ),
        migrations.RemoveField(
            model_name='pendatang',
            name='tanggal_keluar',
        ),
        migrations.RemoveField(
            model_name='pendatang',
            name='wilayah',
        ),
        migrations.AddField(
            model_name='pendatang',
            name='verifikasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendatang',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.PathAndRename('foto_pendatang/')),
        ),
        migrations.AlterField(
            model_name='pendatang',
            name='foto_ktp',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.PathAndRename('ktp_pendatang/')),
        ),
    ]
