# Generated by Django 5.1.7 on 2025-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_pendatang_alamat_asal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendatang',
            name='verifikasi',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
