# Generated by Django 5.1.7 on 2025-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pendatang_verifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendatang',
            name='alasan_tolak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
